#Ejercicio

#Crea un archivo docker-compose.yml para desplegar los servicios de mysql y phpmyadmin, pero
#deberá utilizar la última versión de la imagen de mysql.
#Nota: Es posible que cuando quiera conectarse desde phpmyadmin a mysql obtenga errores
#similares a estos
#• mysqli_real_connect(): The server requested authentication method unknown to the client
#[caching_sha2_password]
#• mysqli_real_connect(): (HY000/2054): The server requested authentication method
#unknown to the client
#Para solucionar este problema deberá sobrescribir el comando con el que se inicia el
#servicio de mysql para indicar que el plugin de autenticación por defecto es de tipo
#mysql_native_password.
#En la sección de definición del servicio de mysql deberá añadir la opción command con el
#siguiente valor.
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data:


  
